#!/bin/sh

export TERM="xterm-256color"
export HISTORY_IGNORE="(ls|cd|pwd|exit|sudo reboot|history|cd -| cd ..)"

export ALIASDOTDIR=$HOME/.config/aliases/
export EXPORTDOTDIR=$HOME/.config/exports/

