#!/bin/sh

alias -g ...="../.."
alias -g ....="../../.."
alias -g .....="../../../.."
alias -g ......="../../../../.."

alias f="$FILE" \
alias e="$EDITOR" \
alias v="$EDITOR" \

alias \
    -- -="cd -" \
    autoremove="sudo apt autoremove" \
    cal="ncal -w -y" \
    cp="cp --interactive --verbose" \
    cpuinfo="cat /proc/cpuinfo" \
    df="df --human-readable" \
    du="du --summarize --total --human-readable" \
    dfind="find -type d -name" \
    dmesg="dmesg --human --color=auto --follow" \
    egrep="egrep --color=auto" \
    ffind="find -type f -name" \
    fgrep="fgrep --color=auto" \
    free="free --human-readable" \
    grep="grep --color=auto" \
    install="sudo apt install" \
    listpackages="apt list --upgradable" \
    ls="ls -l --all --human-readable --color=auto" \
    lsblk="lsblk --all --paths --output +FSTYPE" \
    lshw="sudo lshw" \
    lspci="lspci -tv" \
    lsusb="lsusb -tv" \
    mkdir="mkdir --parents --verbose" \
    mv="mv --interactive --verbose" \
    netstat="netstat -tulanp" \
    open="xdg-open" \
    remove="sudo apt remove" \
    rm="rm --interactive --verbose" \
    tree="tree -C" \
    update="sudo apt update" \
    upgrade="sudo apt upgrade" \
    uptime="uptime --pretty" \
    vi="$EDITOR" \
    vim="$EDITOR" \

alias config="/usr/bin/git --git-dir=${HOME}/.dotfiles --work-tree=${HOME}"

