#!/bin/sh

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="brave-browser"

export ALACRITTYDOTDIR=$HOME/.config/alacritty/
export NVIMDOTDIR=$HOME/.config/nvim/
export TMUXDOTDIR=$HOME/.config/tmux/

